apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\git\choose-your-own-dog\kompose-windows-amd64.exe convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: server
  name: server
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: server
    spec:
      containers:
      - image: "eu.gcr.io/choose-your-own-dog/dog_server:latest"
        name: server
        ports:
        - containerPort: 5000
        resources: {}
      restartPolicy: Always
status: {}
